### ISSUE TITLE
Spotify genre list is only a small subset of the Echo Nest genre list

### ISSUE THREAD

**Issue by monamimani** [spotify/web-api#239]
I would like to have the same genre list with the spotify api that is available with the Echo nest api.
For example spotify api only has blues genre, where the echo nest has blues, chicago blues, delta blues, country blues and a dozen more.

Basicly I'd like to use the same genres as the one in Echo nest database but with the web api.

**Comment by tomkel** [comment]
Please fix, only 133 out of 302 artists and **zero** out of the 356 albums in my library have genres populated. With the echonest [`Artist/terms`](http://developer.echonest.com/docs/v4/artist.html#terms) API endpoint I used to able to categorize all of my music!

**Comment by asmitter** [comment]
We've just pushed out an update to significantly improve genre coverage for artists in the Spotify Web API. For example, "Band of Horses" used to return `["indie folk", "indie pop"]` whereas now it returns `["alternative rock", "chamber pop", "folk-pop", "freak folk", "indie folk", "indie pop", "indie rock", "lo-fi", "singer-songwriter", "stomp and holler"]`
Enjoy the new data!

**Comment by tomkel** [comment]
OK, now 284 / 316 artists in my library have their genres populated. Thanks for the update!

**Comment by tomkel** [comment]
Check out https://tkel.ly/genify/ to see why this data is useful!

**Comment by Dosman** [comment]
Great app tomkel!

**Comment by buckmaxwell** [comment]
I am still missing genre data for 22% of my library including 5% of artists with popularity over 50. Any more plans to beef up genre coverage?
